import { PermissionsBitField, EmbedBuilder } from "discord.js";
import { safeRespond } from "../../utils/helpers.js";
import { asEmbedPayload, buildCoolEmbed } from "../../utils/embeds.js";
import { generateServerRules } from "../../utils/ai.js";

export default {
    data: {
        name: "generate_rules",
        description: "Use AI to generate a custom rules embed for this server",
        default_member_permissions: String(PermissionsBitField.Flags.ManageGuild),
        dm_permission: false,
        options: [
            {
                name: "post_to",
                description: "Channel to post the generated rules in (defaults to current)",
                type: 7,
                required: false,
            },
        ],
    },

    async execute(interaction) {
        if (!interaction.guildId) return;

        await interaction.deferReply({ ephemeral: true });

        const guild = interaction.guild;
        const target = interaction.options.getChannel("post_to") ?? interaction.channel;

        if (!target?.isTextBased()) {
            return safeRespond(interaction, asEmbedPayload({
                guildId: guild.id, type: "error",
                title: "❌ Invalid Channel",
                description: "Selected channel cannot receive messages.",
                ephemeral: true,
            }));
        }

        const channelNames = [...guild.channels.cache.values()]
            .filter(c => c.isTextBased && typeof c.name === "string")
            .map(c => c.name)
            .slice(0, 30);

        const roleNames = [...guild.roles.cache.values()]
            .filter(r => r.id !== guild.id && !r.managed)
            .map(r => r.name)
            .slice(0, 20);

        const rulesText = await generateServerRules({
            name: guild.name,
            channelNames,
            roleNames,
            memberCount: guild.memberCount,
        });

        if (!rulesText || rulesText === "ERROR") {
            return safeRespond(interaction, asEmbedPayload({
                guildId: guild.id, type: "error",
                title: "❌ AI Error",
                description: "Failed to generate rules. Please try again.",
            }));
        }
        if (rulesText === "QUOTA_EXCEEDED") {
            return safeRespond(interaction, asEmbedPayload({
                guildId: guild.id, type: "warning",
                title: "⚠️ Quota Exceeded",
                description: "The AI quota has been reached. Please try again later.",
            }));
        }

        const rulesEmbed = new EmbedBuilder()
            .setColor(0xED4245)
            .setTitle(`📜 ${guild.name} — Server Rules`)
            .setDescription(rulesText.length > 4096 ? rulesText.slice(0, 4093) + "..." : rulesText)
            .setTimestamp()
            .setFooter({ text: "Generated by AI — edit as needed" });

        if (guild.iconURL()) rulesEmbed.setThumbnail(guild.iconURL({ size: 256 }));

        const sent = await target.send({ embeds: [rulesEmbed] }).catch(() => null);

        if (!sent) {
            return safeRespond(interaction, asEmbedPayload({
                guildId: guild.id, type: "error",
                title: "❌ Post Failed",
                description: `Couldn't post in ${target}. Check my permissions there.`,
            }));
        }

        return safeRespond(interaction, asEmbedPayload({
            guildId: guild.id,
            type: "success",
            title: "✅ Rules Generated",
            fields: [
                { name: "📁 Posted In", value: `${target}`, inline: true },
                { name: "🔗 Jump", value: `[Click here](${sent.url})`, inline: true },
                { name: "💡 Tip", value: "You can edit the message to customize anything you don't like.", inline: false },
            ],
        }));
    },
};
