import { safeRespond } from "../../utils/helpers.js";
import { buildCoolEmbed, asEmbedPayload } from "../../utils/embeds.js";
import { getDB } from "../../utils/db.js";
import { getWarningData, afkMap, cosmeticsMap, boosterRolesDB, warnings } from "../../utils/database.js";

const FLAG_BADGES = {
    Staff: "🛡️ Discord Staff",
    Partner: "🤝 Partner",
    Hypesquad: "🎉 HypeSquad Events",
    HypeSquadOnlineHouse1: "🏠 HypeSquad Bravery",
    HypeSquadOnlineHouse2: "🏠 HypeSquad Brilliance",
    HypeSquadOnlineHouse3: "🏠 HypeSquad Balance",
    BugHunterLevel1: "🐛 Bug Hunter",
    BugHunterLevel2: "🐛 Bug Hunter (Gold)",
    PremiumEarlySupporter: "💎 Early Supporter",
    VerifiedDeveloper: "✅ Early Verified Bot Developer",
    CertifiedModerator: "🛡️ Certified Moderator",
    ActiveDeveloper: "👨‍💻 Active Developer",
    VerifiedBot: "🤖 Verified Bot",
};

const STATUS_EMOJI = {
    online: "🟢 Online",
    idle: "🌙 Idle",
    dnd: "⛔ Do Not Disturb",
    offline: "⚫ Offline",
    invisible: "⚫ Invisible",
};

export default {
    data: {
        name: "lookup",
        description: "Retrieve all available bot and guild information about a user by ID",
        options: [
            {
                name: "id",
                description: "The Discord User ID to lookup",
                type: 3, // STRING
                required: true
            }
        ]
    },
    async execute(i) {
        await i.deferReply().catch(() => null);

        const userId = i.options.getString("id").trim();
        
        // Validate ID format (snowflake: 17 to 20 digits)
        if (!/^\d{17,20}$/.test(userId)) {
            return safeRespond(i, asEmbedPayload({
                guildId: i.guild?.id,
                type: "error",
                title: "❌ Invalid ID Format",
                description: "The provided user ID is not a valid Discord Snowflake (must be 17-20 digits).",
                ephemeral: true
            }));
        }

        // Calculate account creation date from Snowflake ID
        const snowflakeTimestamp = Number((BigInt(userId) >> 22n) + 1420070400000n);
        const createdTimestamp = Math.floor(snowflakeTimestamp / 1000);
        const accountAgeDays = Math.floor((Date.now() - snowflakeTimestamp) / (24 * 60 * 60 * 1000));

        // 1. Fetch User from Discord API
        let user = null;
        try {
            user = await i.client.users.fetch(userId);
        } catch (err) {
            // User not found in Discord, but we can still check database for records
        }

        // 2. Fetch Guild Member if in guild where command is run
        const member = i.guild ? await i.guild.members.fetch(userId).catch(() => null) : null;

        const db = await getDB();
        const guildId = i.guild?.id;

        // 3. Database & In-memory Queries
        // Personal Todos
        const todoCount = await db.get("SELECT COUNT(*) AS c FROM todos WHERE user_id = ?", userId).then(r => r?.c ?? 0).catch(() => 0);
        
        // Active Reminders
        const reminderCount = await db.get("SELECT COUNT(*) AS c FROM reminders WHERE user_id = ?", userId).then(r => r?.c ?? 0).catch(() => 0);

        // AFK Info (In-memory Map)
        const afkInfo = afkMap.get(userId);

        // Cosmetics (In-memory Map)
        const cosmeticsInfo = cosmeticsMap.get(userId);

        // Custom Booster Role
        const boosterRoleId = boosterRolesDB.get(userId);

        // Birthday Date (if in guild)
        const birthdayInfo = guildId ? await db.get("SELECT birthday_date FROM birthdays WHERE guild_id = ? AND user_id = ? LIMIT 1", guildId, userId).catch(() => null) : null;

        // Chatbot Conversation History (if in guild)
        let chatMessageCount = 0;
        if (guildId) {
            const chatHistory = await db.get("SELECT messages_json FROM conversation_history WHERE user_id = ? AND guild_id = ?", userId, guildId).catch(() => null);
            if (chatHistory?.messages_json) {
                try {
                    const parsed = JSON.parse(chatHistory.messages_json);
                    chatMessageCount = Array.isArray(parsed) ? parsed.length : 0;
                } catch {}
            }
        }

        // Invite Join Record (if in guild)
        let inviteJoinInfo = null;
        let invitedCount = 0;
        if (guildId) {
            inviteJoinInfo = await db.get("SELECT inviter_id, invite_code, joined_at FROM invite_joins WHERE guild_id = ? AND user_id = ? LIMIT 1", guildId, userId).catch(() => null);
            invitedCount = await db.get("SELECT COUNT(*) AS c FROM invite_joins WHERE guild_id = ? AND inviter_id = ?", guildId, userId).then(r => r?.c ?? 0).catch(() => 0);
        }

        // --- SCAN GUILD ACTIVE INVITE LINKS GENERATED BY USER ---
        const userActiveInvites = [];
        if (guildId && i.guild.members.me.permissions.has("ManageGuild")) {
            try {
                const guildInvites = await i.guild.invites.fetch().catch(() => null);
                if (guildInvites) {
                    const filtered = guildInvites.filter(inv => inv.inviter?.id === userId);
                    for (const inv of filtered.values()) {
                        userActiveInvites.push({
                            code: inv.code,
                            uses: inv.uses,
                            maxUses: inv.maxUses,
                            temporary: inv.temporary,
                            expiresTimestamp: inv.expiresTimestamp
                        });
                    }
                }
            } catch (err) {
                // Ignore permission/fetch errors
            }
        }

        // --- GLOBAL & GUILD MODERATION HISTORY ---
        // Warnings (Current Guild)
        let localWarningCount = 0;
        if (guildId) {
            const warnData = getWarningData(guildId, userId);
            localWarningCount = warnData?.count ?? 0;
        }

        // Warnings (Global - across all servers)
        let globalWarningCount = 0;
        const globalWarningsList = [];
        for (const [key, val] of warnings.entries()) {
            if (key.endsWith(`-${userId}`)) {
                globalWarningCount += val.count;
                const gId = key.substring(0, key.length - userId.length - 1);
                const gName = i.client.guilds.cache.get(gId)?.name || `Unknown Guild (${gId})`;
                
                // Aggregate add actions
                if (val.history) {
                    val.history.forEach(h => {
                        if (h.action === "add") {
                            globalWarningsList.push({
                                guildName: gName,
                                by: h.by,
                                reason: h.reason || "No reason provided",
                                at: h.at
                            });
                        }
                    });
                }
            }
        }

        // Mod Cases (Current Guild vs Global)
        let localModCasesCount = 0;
        let recentLocalModCases = [];
        if (guildId) {
            localModCasesCount = await db.get("SELECT COUNT(*) AS c FROM mod_cases WHERE guild_id = ? AND target_id = ?", guildId, userId).then(r => r?.c ?? 0).catch(() => 0);
            recentLocalModCases = await db.all("SELECT case_number, action, executor_id, reason, duration_ms, created_at FROM mod_cases WHERE guild_id = ? AND target_id = ? ORDER BY case_number DESC LIMIT 3", guildId, userId).catch(() => []);
        }

        // Global Mod Cases (across all guilds)
        const globalModCases = await db.all("SELECT guild_id, case_number, action, executor_id, reason, duration_ms, created_at FROM mod_cases WHERE target_id = ? ORDER BY created_at DESC", userId).catch(() => []);
        const globalModCasesCount = globalModCases.length;

        // Appeals (Current Guild vs Global)
        let localAppeals = [];
        if (guildId) {
            localAppeals = await db.all("SELECT id, status, reason, created_at, resolved_at FROM appeals WHERE guild_id = ? AND user_id = ? ORDER BY created_at DESC LIMIT 3", guildId, userId).catch(() => []);
        }
        const globalAppeals = await db.all("SELECT guild_id, id, status, reason, created_at FROM appeals WHERE user_id = ? ORDER BY created_at DESC", userId).catch(() => []);
        const globalAppealsCount = globalAppeals.length;

        // --- SCAN MUTUAL SERVERS ---
        const mutualServers = [];
        const fetchPromises = Array.from(i.client.guilds.cache.values()).map(async (guild) => {
            try {
                const m = await guild.members.fetch(userId).catch(() => null);
                if (m) {
                    let roleStatus = "Member 👤";
                    if (guild.ownerId === userId) {
                        roleStatus = "Owner 👑";
                    } else if (m.permissions.has("Administrator")) {
                        roleStatus = "Admin ⚙️";
                    } else if (m.permissions.has("BanMembers") || m.permissions.has("KickMembers") || m.permissions.has("ManageGuild") || m.permissions.has("ModerateMembers")) {
                        roleStatus = "Mod 🔧";
                    }
                    mutualServers.push({ name: guild.name, roleStatus });
                }
            } catch {}
        });
        await Promise.all(fetchPromises);

        // --- SECURITY RISK ASSESSMENT ---
        const riskFactors = [];
        const isNewAccount = accountAgeDays < 30;
        const isExtremelyNew = accountAgeDays < 7;
        const hasDefaultAvatar = user ? !user.avatar : true;
        const activeModInfractions = globalModCases.filter(c => ["ban", "kick", "timeout", "softban"].includes(c.action.toLowerCase())).length;

        if (isExtremelyNew) {
            riskFactors.push(`🚨 Account created ${accountAgeDays} days ago (very new)`);
        } else if (isNewAccount) {
            riskFactors.push(`⚠️ Account created ${accountAgeDays} days ago (new)`);
        }

        if (user && hasDefaultAvatar) {
            riskFactors.push(`👤 Default profile image (no custom avatar)`);
        }

        if (globalWarningCount >= 3) {
            riskFactors.push(`🚨 High global warnings count (${globalWarningCount} warnings)`);
        } else if (globalWarningCount > 0) {
            riskFactors.push(`⚠️ Active warnings (${globalWarningCount} globally)`);
        }

        if (activeModInfractions >= 2) {
            riskFactors.push(`🚨 High multi-server infraction history (${activeModInfractions} mod actions)`);
        } else if (activeModInfractions > 0) {
            riskFactors.push(`⚠️ Global mod history (${activeModInfractions} action(s))`);
        }

        // Guild specific key permissions checks
        let hasDangerousPerms = false;
        if (member) {
            const keyPerms = member.permissions?.toArray?.()?.filter(p => [
                "Administrator", "ManageGuild", "ManageRoles", "ManageChannels", "ManageMessages", "BanMembers", "KickMembers", "ModerateMembers"
            ].includes(p)) ?? [];
            if (keyPerms.includes("Administrator")) {
                riskFactors.push(`🔑 Administrator permissions in this server`);
                hasDangerousPerms = true;
            } else if (keyPerms.length > 0) {
                riskFactors.push(`🔑 Sensitive moderator permissions: ${keyPerms.slice(0, 3).join(", ")}`);
                hasDangerousPerms = true;
            }
        }

        // Determine final risk rating
        let riskLevel = "🟢 Low Risk";
        if (isExtremelyNew || globalWarningCount >= 3 || activeModInfractions >= 2) {
            riskLevel = "🔴 High Risk";
        } else if (isNewAccount || hasDefaultAvatar || globalWarningCount > 0 || activeModInfractions > 0 || hasDangerousPerms) {
            riskLevel = "🟡 Medium Risk";
        }

        // 4. Constructing the Embed
        if (!user) {
            // User not found in Discord (invalid ID or deleted user, or bot cannot fetch)
            // But we found database history or can show Snowflake info!
            const embed = buildCoolEmbed({
                guildId,
                type: "warning",
                title: `🔍 ID Audit — ID Not Found on Discord`,
                description: `Unable to fetch active user details from Discord API for ID: \`${userId}\`.\nHowever, metadata and database records exist.`,
                showAuthor: true,
                client: i.client,
            });

            const dbFields = [
                { name: "👤 Snowflake ID Information", value: `**ID:** \`${userId}\`\n**Created At:** <t:${createdTimestamp}:F> (<t:${createdTimestamp}:R>)\n**Account Age:** \`${accountAgeDays} days\``, inline: false }
            ];

            // Add Security Assessment
            const riskValue = riskFactors.length ? riskFactors.join("\n") : "• No security risk factors detected.";
            dbFields.push({ name: `🛡️ Security Risk: ${riskLevel}`, value: riskValue, inline: false });

            // Add Warning details
            if (globalWarningCount > 0) {
                const recentWarns = globalWarningsList.slice(-3).reverse().map(w => `• **[${w.guildName}]** by <@${w.by}>: *${w.reason}*`);
                dbFields.push({ name: `⚠️ Warnings [${globalWarningCount} Global]`, value: recentWarns.join("\n").slice(0, 1024), inline: false });
            }

            // Add Mod cases
            if (globalModCasesCount > 0) {
                const casesText = globalModCases.slice(0, 3).map(c => {
                    const gName = i.client.guilds.cache.get(c.guild_id)?.name || `Unknown Guild (${c.guild_id})`;
                    const actionEmoji = c.action === "ban" ? "🔨" : c.action === "kick" ? "👢" : c.action === "timeout" ? "⏳" : "⚠️";
                    return `• **[${gName}] Case #${c.case_number}** ${actionEmoji} \`${c.action.toUpperCase()}\` by <@${c.executor_id}>: *${String(c.reason || "No reason").slice(0, 60)}*`;
                }).join("\n");
                dbFields.push({ name: `🔨 Moderation Cases [${globalModCasesCount} Global]`, value: casesText.slice(0, 1024), inline: false });
            }

            // Add Appeals
            if (globalAppealsCount > 0) {
                const appealsText = globalAppeals.slice(0, 3).map(a => {
                    const gName = i.client.guilds.cache.get(a.guild_id)?.name || `Unknown Guild (${a.guild_id})`;
                    const statusEmoji = a.status === "accepted" ? "🟢" : a.status === "denied" ? "🔴" : "🟡";
                    return `• **[${gName}] Appeal #${a.id}** ${statusEmoji} \`${a.status.toUpperCase()}\` (Submitted <t:${Math.floor(a.created_at / 1000)}:R>)`;
                }).join("\n");
                dbFields.push({ name: `⚖️ Global Submitted Appeals [${globalAppealsCount}]`, value: appealsText.slice(0, 1024), inline: false });
            }

            // Add Todos & Reminders
            if (todoCount > 0 || reminderCount > 0) {
                dbFields.push({ name: "📝 Bot User Lists", value: `• Todos: \`${todoCount}\`\n• Reminders: \`${reminderCount}\``, inline: true });
            }

            // Add AFK
            if (afkInfo) {
                dbFields.push({ name: "😴 AFK Status", value: `AFK since <t:${Math.floor(afkInfo.since / 1000)}:R>\n*Reason:* ${afkInfo.reason || "None"}`, inline: false });
            }

            // Add Cosmetics
            if (cosmeticsInfo && (cosmeticsInfo.manualTitle || cosmeticsInfo.autoTitle)) {
                dbFields.push({ name: "✨ Cosmetics", value: `• Manual: ${cosmeticsInfo.manualTitle || "None"}\n• Auto: ${cosmeticsInfo.autoTitle || "None"}`, inline: true });
            }

            embed.addFields(dbFields);
            embed.setFooter({
                text: `Requested by ${i.user.tag} • Database & Metadata Mode`,
                iconURL: i.user.displayAvatarURL({ dynamic: true }),
            });

            return safeRespond(i, { embeds: [embed] });
        }

        // User exists!
        const created = `<t:${createdTimestamp}:F> (<t:${createdTimestamp}:R>)`;
        const joined = member?.joinedTimestamp
            ? `<t:${Math.floor(member.joinedTimestamp / 1000)}:F> (<t:${Math.floor(member.joinedTimestamp / 1000)}:R>)`
            : "N/A";

        const flags = user.flags?.toArray?.() ?? [];
        const badges = flags.map(f => FLAG_BADGES[f]).filter(Boolean);
        if (user.bot) badges.unshift("🤖 Bot");
        if (member?.premiumSince) badges.push("💎 Server Booster");

        const status = member?.presence?.status ? STATUS_EMOJI[member.presence.status] : null;
        const activity = member?.presence?.activities?.[0];
        const activityText = activity ? `${activity.type === 4 ? "💬" : "🎮"} ${activity.state || activity.name}` : null;

        const fields = [
            { name: "👤 User Account", value: `**Tag:** \`${user.tag}\`\n**ID:** \`${user.id}\`\n**Mention:** <@${user.id}>\n**Bot:** ${user.bot ? "Yes" : "No"}`, inline: true },
            { name: "📅 Account Created", value: `${created}\n**Age:** \`${accountAgeDays} days\``, inline: true },
        ];

        // Security Risk Assessment Field
        const riskValue = riskFactors.length ? riskFactors.join("\n") : "• No security risk factors detected.";
        fields.push({ name: `🛡️ Security Risk Assessment: ${riskLevel}`, value: riskValue, inline: false });

        // Guild Member details
        if (member) {
            const keyPerms = member.permissions?.toArray?.()?.filter(p => [
                "Administrator", "ManageGuild", "ManageRoles", "ManageChannels", "ManageMessages", "BanMembers", "KickMembers", "ModerateMembers"
            ].includes(p)) ?? [];

            let memberVal = `**Nickname:** ${member.nickname || "None"}\n**Joined:** ${joined}`;
            if (status) memberVal += `\n**Status:** ${status}`;
            if (activityText) memberVal += `\n**Activity:** ${activityText}`;
            if (member.premiumSinceTimestamp) memberVal += `\n**Boosting:** <t:${Math.floor(member.premiumSinceTimestamp / 1000)}:R>`;

            fields.push({ name: "📥 Server Membership", value: memberVal, inline: false });

            // Key permissions
            if (keyPerms.length) {
                fields.push({ name: "🔑 Key Permissions", value: keyPerms.map(p => `\`${p}\``).join(", "), inline: false });
            }

            // Roles
            const roles = member.roles.cache
                .filter((r) => r.id !== i.guild.id)
                .sort((a, b) => b.position - a.position)
                .map((r) => r.toString());
            if (roles.length) {
                const rolesValue = roles.slice(0, 25).join(" ") + (roles.length > 25 ? `\n*+${roles.length - 25} more*` : "");
                fields.push({ name: `🎭 Roles [${roles.length}]`, value: rolesValue.slice(0, 1024), inline: false });
            }
        }

        // Active Invite Links generated by the user in this guild
        if (userActiveInvites.length > 0) {
            const inviteLines = userActiveInvites.slice(0, 5).map(inv => {
                const exp = inv.expiresTimestamp ? `Expires <t:${Math.floor(inv.expiresTimestamp / 1000)}:R>` : "Permanent ♾️";
                const usesInfo = inv.maxUses ? `${inv.uses}/${inv.maxUses} uses` : `${inv.uses} uses`;
                return `• \`${inv.code}\`: **${usesInfo}** • ${exp}${inv.temporary ? " (Temporary)" : ""}`;
            });
            if (userActiveInvites.length > 5) inviteLines.push(`*... and ${userActiveInvites.length - 5} more invite(s)*`);
            fields.push({ name: `🚪 Active Invites Created [${userActiveInvites.length}]`, value: inviteLines.join("\n"), inline: false });
        }

        // Mutual Servers
        if (mutualServers.length > 0) {
            const serverLines = mutualServers.slice(0, 10).map(s => `• **${s.name}** (${s.roleStatus})`);
            if (mutualServers.length > 10) serverLines.push(`*... and ${mutualServers.length - 10} more mutual server(s)*`);
            fields.push({ name: `👥 Mutual Servers [${mutualServers.length}]`, value: serverLines.join("\n"), inline: false });
        }

        // Add badges
        if (badges.length) {
            fields.push({ name: "🏅 Badges", value: badges.join("\n"), inline: true });
        }

        // Database overview
        const dbRecords = [];
        
        // AFK Info
        if (afkInfo) {
            dbRecords.push(`😴 **AFK:** Yes (since <t:${Math.floor(afkInfo.since / 1000)}:R>) — *Reason:* ${afkInfo.reason || "None"}`);
        }

        // Cosmetics
        if (cosmeticsInfo && (cosmeticsInfo.manualTitle || cosmeticsInfo.autoTitle)) {
            dbRecords.push(`✨ **Titles:** ${cosmeticsInfo.manualTitle ? `\`${cosmeticsInfo.manualTitle}\` (Manual)` : ""} ${cosmeticsInfo.autoTitle ? `\`${cosmeticsInfo.autoTitle}\` (Auto)` : ""}`);
        }

        // Booster Role
        if (boosterRoleId) {
            dbRecords.push(`💜 **Custom Booster Role:** <@&${boosterRoleId}>`);
        }

        // Birthday Info
        if (birthdayInfo?.birthday_date) {
            dbRecords.push(`🎂 **Birthday:** \`${birthdayInfo.birthday_date}\``);
        }

        // Personal lists
        if (todoCount > 0 || reminderCount > 0) {
            dbRecords.push(`📝 **User Data:** \`${todoCount}\` Todos • \`${reminderCount}\` Active Reminders`);
        }

        // Chat memory
        if (chatMessageCount > 0) {
            dbRecords.push(`💬 **AI Chat memory:** \`${chatMessageCount}\` messages saved in this guild`);
        }

        // Invites Info
        if (inviteJoinInfo) {
            dbRecords.push(`🚪 **Joined Via:** \`${inviteJoinInfo.invite_code}\` by <@${inviteJoinInfo.inviter_id}> (<t:${Math.floor(inviteJoinInfo.joined_at / 1000)}:R>)`);
        }
        if (invitedCount > 0) {
            dbRecords.push(`🤝 **Invites:** Invited \`${invitedCount}\` users to this server`);
        }

        if (dbRecords.length) {
            fields.push({ name: "🤖 Bot Database Records", value: dbRecords.join("\n").slice(0, 1024), inline: false });
        }

        // Warnings Info
        if (globalWarningCount > 0) {
            const recent = globalWarningsList
                .slice(-3)
                .reverse()
                .map((h) => `• **[${h.guildName}]** <t:${Math.floor(h.at / 1000)}:d> by <@${h.by}>: *${String(h.reason || "No reason").slice(0, 50)}*`);

            let warnText = `**Active Warnings:** \`${globalWarningCount} globally\` (Local: \`${localWarningCount}\`)`;
            if (recent.length) warnText += `\n${recent.join("\n")}`;
            fields.push({ name: "⚠️ Global Warning Record", value: warnText.slice(0, 1024), inline: false });
        }

        // Mod cases history
        if (globalModCasesCount > 0) {
            const casesText = globalModCases.slice(0, 3).map(c => {
                const gName = i.client.guilds.cache.get(c.guild_id)?.name || `Unknown Guild (${c.guild_id})`;
                const actionEmoji = c.action === "ban" ? "🔨" : c.action === "kick" ? "👢" : c.action === "timeout" ? "⏳" : "⚠️";
                return `• **[${gName}] Case #${c.case_number}** ${actionEmoji} \`${c.action.toUpperCase()}\` by <@${c.executor_id}>: *${String(c.reason || "No reason").slice(0, 60)}*`;
            }).join("\n");

            fields.push({ name: `🔨 Global Moderation Cases [${globalModCasesCount}]`, value: casesText.slice(0, 1024), inline: false });
        }

        // Appeals
        if (globalAppealsCount > 0) {
            const appealsText = globalAppeals.slice(0, 3).map(a => {
                const gName = i.client.guilds.cache.get(a.guild_id)?.name || `Unknown Guild (${a.guild_id})`;
                const statusEmoji = a.status === "accepted" ? "🟢" : a.status === "denied" ? "🔴" : "🟡";
                return `• **[${gName}] Appeal #${a.id}** ${statusEmoji} \`${a.status.toUpperCase()}\` (Submitted <t:${Math.floor(a.created_at / 1000)}:R>)`;
            }).join("\n");
            fields.push({ name: `⚖️ Global Submitted Appeals [${globalAppealsCount}]`, value: appealsText.slice(0, 1024), inline: false });
        }

        const embed = buildCoolEmbed({
            guildId,
            type: member ? "info" : "general",
            title: `🔍 User Audit & Information — ${user.tag}`,
            description: `<@${user.id}>`,
            fields,
            showAuthor: true,
            showFooter: false,
            client: i.client,
        });

        embed.setThumbnail(user.displayAvatarURL({ dynamic: true, size: 256 }));

        const banner = user.bannerURL?.({ size: 1024, dynamic: true });
        if (banner) embed.setImage(banner);

        if (user.accentColor) embed.setColor(user.accentColor);
        else if (member?.displayHexColor && member.displayHexColor !== "#000000") embed.setColor(member.displayHexColor);

        // Adjust color based on risk rating to visually stand out
        if (riskLevel === "🔴 High Risk") embed.setColor(0xed4245); // Red
        else if (riskLevel === "🟡 Medium Risk") embed.setColor(0xfee75c); // Yellow

        embed.setFooter({
            text: `Requested by ${i.user.tag} • ID: ${user.id}`,
            iconURL: i.user.displayAvatarURL({ dynamic: true }),
        });

        return safeRespond(i, { embeds: [embed] });
    }
};
